import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import test from 'node:test';

const schema = readFileSync('supabase/schema.sql', 'utf8').replaceAll('\r\n', '\n');
const migrationNames = readdirSync('supabase/migrations')
  .filter((name) => name.endsWith('.sql'))
  .sort();

const expectedTables = [
  'alert_events',
  'apps',
  'issue_cluster_reviews',
  'issue_cluster_snapshots',
  'issue_clusters',
  'parse_errors',
  'pipeline_job_claims',
  'pipeline_jobs',
  'pipeline_review_ai_staging',
  'pipeline_runs',
  'review_ai',
  'reviews',
];

const expectedFunctions = [
  'cancel_pipeline_jobs',
  'claim_pipeline_job',
  'complete_pipeline_job',
  'enqueue_pipeline_job',
  'get_existing_review_ids',
  'get_pipeline_cluster_context',
  'get_pipeline_cluster_context_v2',
  'get_pipeline_review_scope',
  'get_public_apps',
  'get_public_categories',
  'get_public_issue_clusters',
  'get_public_issue_clusters_windowed',
  'get_public_issue_detail',
  'get_public_issue_detail_windowed',
  'get_public_issues',
  'get_public_overview',
  'get_public_trends',
  'guard_pipeline_job_transition',
  'normalize_review_category',
  'persist_issue_clusters',
  'persist_pipeline_alerts',
  'persist_pipeline_reviews',
  'prepare_account_deletion',
  'publish_pipeline_run',
  'record_pipeline_parse_error',
  'reject_pipeline_job_stage_regression',
  'renew_pipeline_job_claim',
];

const serviceOnlyFunctions = [
  'cancel_pipeline_jobs',
  'claim_pipeline_job',
  'complete_pipeline_job',
  'enqueue_pipeline_job',
  'get_existing_review_ids',
  'get_pipeline_cluster_context',
  'get_pipeline_cluster_context_v2',
  'get_pipeline_review_scope',
  'get_public_apps',
  'get_public_issue_clusters',
  'get_public_issue_clusters_windowed',
  'get_public_issue_detail',
  'get_public_issue_detail_windowed',
  'persist_issue_clusters',
  'persist_pipeline_alerts',
  'persist_pipeline_reviews',
  'prepare_account_deletion',
  'publish_pipeline_run',
  'record_pipeline_parse_error',
  'renew_pipeline_job_claim',
];

function migration(name) {
  return readFileSync(`supabase/migrations/${name}`, 'utf8').replaceAll('\r\n', '\n');
}

test('migration ledger keeps the complete ordered upgrade history', () => {
  assert.ok(migrationNames.length > 0);
  assert.equal(new Set(migrationNames).size, migrationNames.length);
  for (const migrationName of migrationNames) {
    assert.match(migrationName, /^\d{12,14}_[a-z0-9_]+\.sql$/);
    assert.ok(readFileSync(`supabase/migrations/${migrationName}`, 'utf8').trim().length > 0);
  }
});

test('fresh schema identifies its deterministic PostgreSQL 17 generation path', () => {
  assert.match(schema, /^-- Generated fresh-install snapshot\. Do not edit this file directly\./);
  assert.match(schema, /-- Refresh: node scripts\/generate-supabase-schema\.mjs/);
  assert.match(schema, /-- Check: node scripts\/generate-supabase-schema\.mjs --check/);
  assert.match(schema, /^CREATE EXTENSION IF NOT EXISTS pgcrypto;$/m);
});

test('fresh schema contains one final definition per project function', () => {
  const functionNames = [...schema.matchAll(/^CREATE FUNCTION public\.([a-z0-9_]+)\(/gm)]
    .map((match) => match[1]);
  assert.deepEqual(functionNames.sort(), [...expectedFunctions].sort());
  assert.equal(new Set(functionNames).size, functionNames.length);
  assert.doesNotMatch(schema, /^CREATE OR REPLACE FUNCTION /m);
});

test('fresh schema has final objects without migration backfills', () => {
  const tableNames = [...schema.matchAll(/^CREATE TABLE public\.([a-z0-9_]+) \(/gm)]
    .map((match) => match[1]);
  assert.deepEqual(tableNames.sort(), [...expectedTables].sort());
  assert.doesNotMatch(schema, /^(?:UPDATE|DELETE FROM|INSERT INTO) public\./m);
  assert.doesNotMatch(schema, /\bADD COLUMN IF NOT EXISTS\b/i);
  assert.doesNotMatch(schema, /^ALTER DEFAULT PRIVILEGES /m);
  assert.match(schema, /^CREATE VIEW public\.private_review_feed WITH \(security_invoker='true'\) AS$/m);
});

test('every public table enables RLS and the final policies are present', () => {
  for (const tableName of expectedTables) {
    assert.match(schema, new RegExp(`^ALTER TABLE public\\.${tableName} ENABLE ROW LEVEL SECURITY;$`, 'm'));
  }
  for (const policyName of [
    'apps_read_public',
    'pipeline_jobs_select_own',
    'review_ai_read_authenticated',
    'reviews_read_authenticated',
  ]) {
    assert.match(schema, new RegExp(`^CREATE POLICY ${policyName} ON public\\.`, 'm'));
  }
  assert.match(schema, /requested_by = \( SELECT auth\.uid\(\) AS uid\)/);
});

test('snapshot carries explicit Data API object grants independent of project defaults', () => {
  for (const tableName of ['apps', 'reviews', 'review_ai']) {
    for (const role of ['anon', 'authenticated', 'service_role']) {
      assert.match(
        schema,
        new RegExp(`^GRANT [^;]+ ON TABLE public\\.${tableName} TO ${role};$`, 'm'),
      );
    }
  }
  const authenticatedGrant = schema.match(/^GRANT ([^;]+) ON TABLE public\.pipeline_jobs TO authenticated;$/m);
  const serviceRoleGrant = schema.match(/^GRANT ([^;]+) ON TABLE public\.pipeline_jobs TO service_role;$/m);
  assert.ok(authenticatedGrant);
  assert.ok(serviceRoleGrant);
  assert.match(authenticatedGrant[1], /\bSELECT\b/);
  assert.doesNotMatch(authenticatedGrant[1], /\bINSERT\b/);
  assert.match(serviceRoleGrant[1], /\bINSERT\b/);
});

test('SECURITY DEFINER RPCs keep their final service-role boundary', () => {
  for (const functionName of serviceOnlyFunctions) {
    assert.match(
      schema,
      new RegExp(
        `^REVOKE ALL ON FUNCTION public\\.${functionName}\\([^;]+ FROM PUBLIC, anon, authenticated, service_role;$`,
        'm',
      ),
    );
    assert.match(
      schema,
      new RegExp(`^GRANT ALL ON FUNCTION public\\.${functionName}\\([^;]+ TO service_role;$`, 'm'),
    );
    assert.doesNotMatch(
      schema,
      new RegExp(`^GRANT ALL ON FUNCTION public\\.${functionName}\\([^;]+ TO (?:anon|authenticated);$`, 'm'),
    );
  }
  assert.match(schema, /-- Normalize object ACLs independently of target-project default privileges\./);
  for (const tableName of expectedTables) {
    assert.match(
      schema,
      new RegExp(
        `^REVOKE ALL ON TABLE public\\.${tableName} FROM PUBLIC, anon, authenticated, service_role;$`,
        'm',
      ),
    );
  }
});

test('final trigger and index contracts are materialized once', () => {
  assert.match(
    schema,
    /^CREATE TRIGGER pipeline_jobs_reject_stage_regression .*public\.reject_pipeline_job_stage_regression\(\);$/m,
  );
  assert.match(
    schema,
    /^CREATE TRIGGER trg_guard_pipeline_job_transition .*public\.guard_pipeline_job_transition\(\);$/m,
  );
  for (const indexName of [
    'idx_issue_cluster_reviews_review',
    'idx_issue_clusters_current_run',
    'idx_pipeline_review_ai_staging_review_scope',
    'idx_pipeline_runs_public_app_directory',
    'uq_reviews_id_scope',
  ]) {
    assert.equal((schema.match(new RegExp(`^CREATE (?:UNIQUE )?INDEX ${indexName} `, 'gm')) || []).length, 1);
  }
});

test('historical security migrations remain upgrade-only contracts', () => {
  const hardening = migration('20260721022747_harden_internal_rpc_privileges.sql');
  const enqueuePrepare = migration('202607290001_prepare_pipeline_job_enqueue.sql');
  const enqueueHarden = migration('202607290003_harden_pipeline_job_enqueue.sql');

  assert.match(hardening, /revoke execute on function public\.claim_pipeline_job\(text, text, text\)\s+from public, anon, authenticated;/i);
  assert.match(hardening, /grant execute on function public\.claim_pipeline_job\(text, text, text\)\s+to service_role;/i);
  assert.match(enqueuePrepare, /grant insert on table public\.pipeline_jobs to service_role;/i);
  assert.doesNotMatch(enqueuePrepare, /revoke\s+insert\s+on\s+table\s+public\.pipeline_jobs/i);
  assert.match(enqueueHarden, /revoke insert on table public\.pipeline_jobs from public, anon, authenticated;/i);
  assert.doesNotMatch(enqueueHarden, /grant insert on table public\.pipeline_jobs to service_role;/i);
});
